apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: maneki
  source:
    repoURL: https://github.com/masa213f/test-apps.git
    targetRevision: main
    path: manifests/test
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
